# Generated by Django 4.1.6 on 2023-03-16 01:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can view history")],
            },
        ),
    ]
