version: '3.10'

services:
  backend:
    build: .
    # command: python manage.py runserver 0.0.0.0:8001
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=abcdef1234
      - DATABASE_NAME=slidery
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password1234
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
    volumes:
      - .:/app
    
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432' # Use 5444 because default psql in computer use 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: slidery
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/db:/var/lib/postgresql/data
