version: '3.10'

services:
    
  db:
    image: postgres:15-alpine
    ports:
      - '5444:5444'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: slidery
    volumes:
      - ./data/db:/var/lib/postgresql/data
    command: -p 5444
  
  backend:
    build: .
    command: > 
      sh -c "source scripts/setup_docker.sh"
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=abcdef1234
      - DATABASE_NAME=slidery
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password1234
      - DATABASE_PORT=5444
      - DATABASE_HOST=db
    volumes:
      - .:/app
